# Generated by Django 3.1.6 on 2021-03-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210313_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_background',
            new_name='Background',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_designation',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='work_experience',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_schedule',
            new_name='Schedule',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_image',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Image',
            field=models.ImageField(null=True, upload_to='static/uploads'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_email',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
