# Generated by Django 3.1.6 on 2021-03-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210313_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_email',
            new_name='Email',
        ),
    ]
