# Generated by Django 3.1.6 on 2021-03-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210313_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads'),
        ),
    ]
